# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QtApp.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1103, 700)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        self.startButton.setGeometry(QtCore.QRect(0, 540, 191, 101))
        self.startButton.setObjectName("startButton")
        self.chartView = QtWebEngineWidgets.QWebEngineView(self.centralwidget)
        self.chartView.setGeometry(QtCore.QRect(210, 30, 861, 451))
        self.chartView.setUrl(QtCore.QUrl("about:blank"))
        self.chartView.setObjectName("chartView")
        self.frame_input = QtWidgets.QFrame(self.centralwidget)
        self.frame_input.setGeometry(QtCore.QRect(10, 10, 171, 511))
        self.frame_input.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_input.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_input.setObjectName("frame_input")
        self.label_input = QtWidgets.QLabel(self.frame_input)
        self.label_input.setGeometry(QtCore.QRect(0, 0, 158, 31))
        self.label_input.setObjectName("label_input")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.frame_input)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 340, 160, 131))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_action = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_action.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_action.setObjectName("verticalLayout_action")
        self.label_action = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_action.setObjectName("label_action")
        self.verticalLayout_action.addWidget(self.label_action)
        self.radioButton_fast = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_fast.setChecked(True)
        self.radioButton_fast.setObjectName("radioButton_fast")
        self.verticalLayout_action.addWidget(self.radioButton_fast)
        self.radioButton_standar = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_standar.setObjectName("radioButton_standar")
        self.verticalLayout_action.addWidget(self.radioButton_standar)
        self.radioButton_slow = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_slow.setChecked(False)
        self.radioButton_slow.setObjectName("radioButton_slow")
        self.verticalLayout_action.addWidget(self.radioButton_slow)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_action.addItem(spacerItem)
        self.label_money = QtWidgets.QLabel(self.frame_input)
        self.label_money.setGeometry(QtCore.QRect(10, 470, 91, 41))
        self.label_money.setObjectName("label_money")
        self.plainTextEdit_money = QtWidgets.QPlainTextEdit(self.frame_input)
        self.plainTextEdit_money.setGeometry(QtCore.QRect(60, 480, 111, 31))
        self.plainTextEdit_money.setObjectName("plainTextEdit_money")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.frame_input)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(0, 200, 160, 131))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_date = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_date.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_date.setObjectName("verticalLayout_date")
        self.label_startDate = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_startDate.setObjectName("label_startDate")
        self.verticalLayout_date.addWidget(self.label_startDate)
        self.dateEdit_startDate = QtWidgets.QDateEdit(self.verticalLayoutWidget_3)
        self.dateEdit_startDate.setDateTime(QtCore.QDateTime(QtCore.QDate(2021, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateEdit_startDate.setObjectName("dateEdit_startDate")
        self.verticalLayout_date.addWidget(self.dateEdit_startDate)
        self.label_endDate = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_endDate.setObjectName("label_endDate")
        self.verticalLayout_date.addWidget(self.label_endDate)
        self.dateEdit_endDate = QtWidgets.QDateEdit(self.verticalLayoutWidget_3)
        self.dateEdit_endDate.setDateTime(QtCore.QDateTime(QtCore.QDate(2021, 12, 31), QtCore.QTime(0, 0, 0)))
        self.dateEdit_endDate.setObjectName("dateEdit_endDate")
        self.verticalLayout_date.addWidget(self.dateEdit_endDate)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.frame_input)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(0, 30, 158, 166))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_stock = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_stock.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_stock.setObjectName("verticalLayout_stock")
        self.label_source = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_source.setObjectName("label_source")
        self.verticalLayout_stock.addWidget(self.label_source)
        self.comboBox_source = QtWidgets.QComboBox(self.verticalLayoutWidget_4)
        self.comboBox_source.setObjectName("comboBox_source")
        self.comboBox_source.addItem("")
        self.verticalLayout_stock.addWidget(self.comboBox_source)
        self.label_stock = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_stock.setObjectName("label_stock")
        self.verticalLayout_stock.addWidget(self.label_stock)
        self.listWidget_stock = QtWidgets.QListWidget(self.verticalLayoutWidget_4)
        self.listWidget_stock.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.listWidget_stock.setObjectName("listWidget_stock")
        self.verticalLayout_stock.addWidget(self.listWidget_stock)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1103, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.startButton.setText(_translate("MainWindow", "PushButton"))
        self.label_input.setText(_translate("MainWindow", "Input"))
        self.label_action.setText(_translate("MainWindow", "Select action"))
        self.radioButton_fast.setText(_translate("MainWindow", "Fast"))
        self.radioButton_standar.setText(_translate("MainWindow", "Standar"))
        self.radioButton_slow.setText(_translate("MainWindow", "Slow"))
        self.label_money.setText(_translate("MainWindow", "Money"))
        self.plainTextEdit_money.setPlainText(_translate("MainWindow", "1000"))
        self.label_startDate.setText(_translate("MainWindow", "Start Date"))
        self.label_endDate.setText(_translate("MainWindow", "End Date"))
        self.label_source.setText(_translate("MainWindow", "Select Stock Source"))
        self.comboBox_source.setItemText(0, _translate("MainWindow", "IBEX35"))
        self.label_stock.setText(_translate("MainWindow", "Select Stocks from source"))
from PyQt5 import QtWebEngineWidgets


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
